### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by NiceLeader** [OwOHamper/lolesports.com-watcher#3]
![Bez tytułu (2)](https://user-images.githubusercontent.com/54146337/185167229-72a31d7d-25d3-4439-8a6d-e172f925e836.png)
i used script for month and then this happened

**Comment by teoobarca** [comment]
Not sure what's the issue here, restarting should do the job.

**Comment by NiceLeader** [comment]
i tried restarted etc. but didnt help . I even reinstalled python

**Comment by teoobarca** [comment]
What version of python are you using?
